# Generated by Django 5.0.6 on 2026-05-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_systemsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('verdict_number', models.CharField(max_length=255, unique=True)),
                ('verdict', models.TextField(blank=True, default='')),
                ('dispute', models.TextField(blank=True, default='')),
                ('legal_basis', models.TextField(blank=True, default='')),
                ('djp', models.TextField(blank=True, default='')),
                ('taxpayer', models.TextField(blank=True, default='')),
                ('assembly_decision', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
