"""
Research Subagent — web-research nodes for the TP documentation workflow.

Nodes:
  - research_industry_global      → industry_analysis_global, industry_global_sources
  - research_industry_indonesia   → industry_analysis_indonesia, industry_indonesia_sources
  - research_business_environment → business_environment_overview
  - research_company_location     → company_location_analysis, company_location_sources
  - research_industry_regulations → industry_regulations_text, industry_regulations_sources
"""
import json
import re
from agents.llm_factory import invoke_prompt_with_tools
from agents.tools import UNTRUSTED_DATA_NOTICE, sanitize_search_results, search_web


def _strip_source_summary(text: str) -> str:
    """
    Remove model-added source summary blocks such as
    "Sources (footnotes): [1] ... [2] ..." from section bodies.
    Source URLs are rendered separately by the exporter.
    """
    cleaned = re.sub(
        r"\n+\s*(sources?\s*(\([^)]*\))?\s*:|footnotes?\s*:).*$",
        "",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )
    return cleaned.strip()


# ─── Node: Industry Analysis (Global) ────────────────────────────────────────

def research_industry_global(state: dict) -> dict:
    """Research global industry analysis based on company's products/sector."""
    products = state.get("products", [])
    product_names = ", ".join([p.get("name", "") for p in products]) if products else "heavy equipment"
    business_desc = state.get("business_activities_description", "")
    industry_hint = product_names or "heavy equipment, construction machinery"

    raw1 = search_web(
        f"global {industry_hint} industry market size 2024 2025 growth CAGR forecast",
        max_results=5,
    )
    raw2 = search_web(
        f"global {industry_hint} market major players companies competition",
        max_results=3,
    )

    results1 = sanitize_search_results(raw1.get("results", []), max_results=5)
    results2 = sanitize_search_results(raw2.get("results", []), max_results=3)
    # Tavily's own summary is generated by Tavily's LLM — still sanitize for safety
    tavily_summary = raw1.get("answer", "N/A")[:500]

    prompt = f"""You are a transfer pricing analyst writing the Global Industry Analysis section of a Transfer Pricing Local File document for an Indonesian company.

Company context:
- Products/services: {product_names}
- Business description: {business_desc[:500]}

{UNTRUSTED_DATA_NOTICE}
Web research results on global industry:
{json.dumps(results1, indent=2)[:2500]}

Additional research on competition:
{json.dumps(results2, indent=2)[:1500]}

Tavily's summary answer: {tavily_summary}

Write a comprehensive Global Industry Analysis section (3-5 paragraphs) covering:
1. Definition and scope of the industry
2. Global market size (with specific USD figures and CAGR if available)
3. Key growth drivers and trends
4. Regional dynamics (especially Asia-Pacific)
5. Major global players/competitors

IMPORTANT RULES:
- RESPOND IN ENGLISH ONLY. Do NOT switch to Indonesian or any other language.
- Use ONLY factual data from the search results. Do NOT invent statistics.
- If a specific number is not available in the research, state the trend qualitatively instead.
- Cite sources where possible (e.g., "According to [source]...")
- Write in formal, professional English suitable for a tax compliance document.
- Do NOT include section headers — just flowing paragraphs.
- Include footnote markers like [1], [2] for source references.
- Do NOT append a "Sources", "Footnotes", or reference-summary section at the end.
"""
    response_text = _strip_source_summary(invoke_prompt_with_tools(prompt))
    sources = [r.get("url", "") for r in results1]

    return {
        "industry_analysis_global": response_text,
        "industry_global_sources": sources,
    }


# ─── Node: Industry Analysis (Indonesia) ─────────────────────────────────────

def research_industry_indonesia(state: dict) -> dict:
    """Research Indonesian industry analysis."""
    products = state.get("products", [])
    product_names = ", ".join([p.get("name", "") for p in products]) if products else "heavy equipment"

    raw1 = search_web(
        f"Indonesia {product_names} industry market 2024 growth regulations government policy",
        max_results=5,
    )
    raw2 = search_web(
        f"Indonesia {product_names} market competition domestic companies regulations mining construction",
        max_results=3,
    )

    results1 = sanitize_search_results(raw1.get("results", []), max_results=5)
    results2 = sanitize_search_results(raw2.get("results", []), max_results=3)
    tavily_summary = raw1.get("answer", "N/A")[:500]

    prompt = f"""You are a transfer pricing analyst writing the Indonesian Industry Analysis section of a Transfer Pricing Local File document.

Company products/services: {product_names}

{UNTRUSTED_DATA_NOTICE}
Web research results on Indonesian market:
{json.dumps(results1, indent=2)[:2500]}

Additional research:
{json.dumps(results2, indent=2)[:1500]}

Tavily's summary: {tavily_summary}

Write a comprehensive Indonesian Industry Analysis section (3-5 paragraphs) covering:
1. Role of the industry in Indonesia's economy
2. Market size and growth in Indonesia
3. Key domestic and foreign competitors in Indonesia
4. Government policies and regulations affecting the industry
5. Infrastructure development and market outlook

IMPORTANT RULES:
- RESPOND IN ENGLISH ONLY. Do NOT switch to Indonesian or any other language.
- Use ONLY factual data from the search results. Do NOT invent statistics.
- If specific numbers aren't available, describe trends qualitatively.
- Write in formal professional English for a tax compliance document.
- Do NOT include section headers.
- Include footnote markers [1], [2] for source references.
- Do NOT append a "Sources", "Footnotes", or reference-summary section at the end.
"""
    response_text = _strip_source_summary(invoke_prompt_with_tools(prompt))
    sources = [r.get("url", "") for r in results1]

    return {
        "industry_analysis_indonesia": response_text,
        "industry_indonesia_sources": sources,
    }


# ─── Node: Business Environment / Competitors ────────────────────────────────

def research_business_environment(state: dict) -> dict:
    """Research the competitive business environment."""
    company_name = state.get("company_name", "")
    parent_group = state.get("parent_group", "")
    products = state.get("products", [])
    product_names = ", ".join([p.get("name", "") for p in products]) if products else "heavy equipment"

    raw = search_web(
        f"{parent_group} {product_names} Indonesia competitors market share",
        max_results=5,
    )
    results = sanitize_search_results(raw.get("results", []), max_results=5)

    prompt = f"""You are a transfer pricing analyst writing the Business Environment Overview section.

Company: {company_name}
Parent group: {parent_group}
Products: {product_names}

{UNTRUSTED_DATA_NOTICE}
Web research:
{json.dumps(results, indent=2)[:2500]}

Write 2-3 paragraphs about:
1. The competitive landscape for this company's products in Indonesia
2. Main competitors (both domestic and international)
3. Market positioning of the company/group

RULES:
- RESPOND IN ENGLISH ONLY. Do NOT switch to Indonesian or any other language.
- Only use factual information from search results
- Formal professional English
- No section headers
- Include footnote markers [1], [2] for source references.
- Do NOT append a "Sources", "Footnotes", or reference-summary section at the end.
"""
    response_text = _strip_source_summary(invoke_prompt_with_tools(prompt))
    sources = list(dict.fromkeys(r.get("url", "") for r in results if r.get("url")))
    return {
        "business_environment_overview": response_text,
        "business_environment_sources":  sources,
    }


# ─── Node: Company Location Analysis (Sec 5.1.2.1) ───────────────────────────

def research_company_location(state: dict) -> dict:
    """
    Research economic/business efficiency factors for the company's location.

    Covers Inflation Rate, Economic Growth, and Exchange Rate using Tavily
    web search, then generates structured Section 5.1.2.1 content.

    Returns:
        company_location_analysis: str  — formatted paragraphs
        company_location_sources:  list — source URLs
    """
    company_address = state.get("company_address", "")
    fiscal_year     = state.get("fiscal_year", "2024")
    products        = state.get("products", [])
    product_names   = ", ".join(p.get("name", "") for p in products if p.get("name")) or "general"

    # Extract city/province from address (use first meaningful token)
    _location_tokens = [t.strip() for t in company_address.replace(",", " ").split() if len(t.strip()) > 3]
    location = " ".join(_location_tokens[:3]) if _location_tokens else "Indonesia"

    # ── Tavily searches ──────────────────────────────────────────────────────
    raw_inflation = search_web(
        f"Indonesia inflation rate CPI {fiscal_year} Bank Indonesia BPS data",
        max_results=4,
    )
    raw_gdp = search_web(
        f"Indonesia economic growth GDP {fiscal_year} quarter BPS statistics",
        max_results=4,
    )
    raw_fx = search_web(
        f"Indonesia Rupiah IDR exchange rate USD {fiscal_year} Bank Indonesia",
        max_results=3,
    )

    results_inflation = sanitize_search_results(raw_inflation.get("results", []), max_results=4)
    results_gdp       = sanitize_search_results(raw_gdp.get("results",  []), max_results=4)
    results_fx        = sanitize_search_results(raw_fx.get("results",   []), max_results=3)

    tavily_inf = raw_inflation.get("answer", "N/A")[:400]
    tavily_gdp = raw_gdp.get("answer", "N/A")[:400]

    # Collect unique sources
    all_results = results_inflation + results_gdp + results_fx
    sources = list(dict.fromkeys(r.get("url", "") for r in all_results if r.get("url")))

    prompt = f"""You are a transfer pricing analyst writing Section 5.1.2.1 "Efficiency and Excellence Levels of Company Locations" of a Transfer Pricing Local File document.

Company context:
- Company location / address: {company_address or location}
- Products/services: {product_names}
- Fiscal year: {fiscal_year}

{UNTRUSTED_DATA_NOTICE}

=== Research: Inflation Rate ===
{json.dumps(results_inflation, indent=2)[:1800]}
Tavily summary: {tavily_inf}

=== Research: Economic Growth / GDP ===
{json.dumps(results_gdp, indent=2)[:1800]}
Tavily summary: {tavily_gdp}

=== Research: Exchange Rate ===
{json.dumps(results_fx, indent=2)[:1200]}

Write a professional section covering the economic efficiency factors that affect business performance in the company's location in Indonesia. Structure the content as follows, using the EXACT pattern:

**Inflation Rate;**
[1–2 paragraphs with specific CPI figures, y-o-y change, BI target range, trend outlook. Cite footnotes like [1], [2].]

**Economic Growth;**
[1–2 paragraphs with GDP q-t-q / y-t-y / c-t-c growth figures, province contribution, outlook. Cite footnotes.]

**Exchange Rate/Exchange Rate;**
[1–2 paragraphs with IDR/USD bid rate, SBN yield, DXY movement, trend. Cite footnotes.]

IMPORTANT RULES:
- RESPOND IN ENGLISH ONLY.
- Use ONLY factual data from the search results. Do NOT invent numbers.
- Include a brief intro sentence before the first bullet: "There are several factors that affect business performance in the [industry] industry in [location], as follows:"
- Use **bold label;** followed by a newline for each factor heading.
- Include source citations [N] inline where data is referenced.
- Formal, professional English suitable for a tax compliance document.
- Do NOT add any section heading — start directly with the intro sentence.
- Do NOT append a "Sources", "Footnotes", or reference-summary section at the end.
"""
    response_text = _strip_source_summary(invoke_prompt_with_tools(prompt))
    return {
        "company_location_analysis": response_text,
        "company_location_sources":  sources,
    }


# ─── Node: Industry Regulations (Sec 5.1.2.2) ──────────────────────────────────────

def research_industry_regulations(state: dict) -> dict:
    """
    Research Indonesian government regulations that affect the company's industry.

    Uses Tavily to find relevant Ministry regulations, standards, and policies,
    then generates Section 5.1.2.2 content as a bulleted list of regulation titles
    with explanatory paragraphs.

    Returns:
        industry_regulations_text:    str  — formatted bulleted regulation entries
        industry_regulations_sources: list — source URLs
    """
    products        = state.get("products", [])
    product_names   = ", ".join(p.get("name", "") for p in products if p.get("name")) or "heavy equipment"
    fiscal_year     = state.get("fiscal_year", "2024")

    # ── Tavily searches ──────────────────────────────────────────────────────
    raw_regs = search_web(
        f"Indonesia regulation Ministry peraturan {product_names} industry SNI standard import 2023 2024",
        max_results=5,
    )
    raw_policy = search_web(
        f"Indonesia government policy regulation {product_names} industry Ministry of Industry Trade 2024",
        max_results=4,
    )

    results_regs   = sanitize_search_results(raw_regs.get("results",   []), max_results=5)
    results_policy = sanitize_search_results(raw_policy.get("results", []), max_results=4)

    tavily_regs = raw_regs.get("answer", "N/A")[:500]

    all_results = results_regs + results_policy
    sources = list(dict.fromkeys(r.get("url", "") for r in all_results if r.get("url")))

    prompt = f"""You are a transfer pricing analyst writing Section 5.1.2.2 "Regulations Affecting the Industry" of a Transfer Pricing Local File document for an Indonesian company.

Company products/services: {product_names}
Fiscal year: {fiscal_year}

{UNTRUSTED_DATA_NOTICE}

=== Research: Indonesian Industry Regulations ===
{json.dumps(results_regs, indent=2)[:2500]}
Tavily summary: {tavily_regs}

=== Research: Government Policy ===
{json.dumps(results_policy, indent=2)[:2000]}

Write a professional section listing the key Indonesian government regulations that affect the {product_names} industry. Use the following EXACT format for each regulation:

- [Exact regulation name, e.g. "Regulation of the Minister of Industry No. XX/M-IND/PER/X/XXXX concerning ..."]\n[1–2 sentences explaining what the regulation covers and how it affects companies in this industry.]

List 3–5 relevant regulations. Each entry must:
- Start with a bullet point (• or -) followed by the official regulation title in bold
- Follow immediately with a plain-text explanation paragraph
- Include a citation like [1], [2] where the data comes from

IMPORTANT RULES:
- RESPOND IN ENGLISH ONLY.
- Only include regulations that are factually supported by the search results. Do NOT invent regulation numbers.
- If a specific regulation number is not available from the research, describe the policy type generically.
- Formal, professional English suitable for a tax compliance document.
- Do NOT include a section heading — start directly with the first bullet.
- Do NOT append a "Sources", "Footnotes", or reference-summary section at the end.
"""
    response_text = _strip_source_summary(invoke_prompt_with_tools(prompt))
    return {
        "industry_regulations_text":    response_text,
        "industry_regulations_sources": sources,
    }


# ─── Node: Comparable Companies Research ──────────────────────────────────────

def research_comparable_companies(state: dict) -> dict:
    """
    Research each comparable company using Tavily and generate a business
    description paragraph for Appendix 3.

    Returns:
        comparable_descriptions: dict  — {company_name: ai_description}
    """
    companies = [
        c for c in state.get("comparable_companies", []) if c.get("name")
    ]
    if not companies:
        return {"comparable_descriptions": {}}

    descriptions = {}

    for company in companies:
        name    = company.get("name", "")
        country = company.get("country", "")

        raw = search_web(
            f"{name} company business activities overview {country}",
            max_results=3,
        )
        results = sanitize_search_results(raw.get("results", []), max_results=3)
        tavily_answer = raw.get("answer", "")[:400]

        prompt = f"""You are a transfer pricing analyst writing Appendix 3 "Overview of Comparable Companies" in a Transfer Pricing Local File.

Write a concise business description (3–5 sentences) for the following company to be used as a comparable company entry:

Company name: {name}
Country: {country or "not specified"}

{UNTRUSTED_DATA_NOTICE}
Web research results:
{json.dumps(results, indent=2)[:2000]}
Tavily summary: {tavily_answer}

Rules:
- Describe the company's main business activities, products/services, and markets served
- Write in formal transfer pricing documentation English
- RESPOND IN ENGLISH ONLY
- Do NOT invent figures or facts not supported by the research
- No bullet points — write plain flowing sentences only
- Do NOT include the company name as a heading"""

        try:
            text = invoke_prompt_with_tools(prompt).strip()
        except Exception:
            text = f"{name} is a company operating in {country or 'its home country'}."

        descriptions[name] = text

    return {"comparable_descriptions": descriptions}
